{{ if .Values.mysqlProxy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-proxy
  template:
    metadata:
      labels:
        name: db-proxy
        app: db-proxy
    spec:
      containers:
      - name: db-proxy
        image: {{ tpl .Values.dbProxy.image.template . | quote }}
        env:
          {{- with .Values.mysql }}
          {{- $sections := untilStep 1 9 1 | toStrings }}
          {{- $domain := .domain }}
          {{- range $sections }}
          - name: {{ printf "SEC%s_HOST" . | quote }}
            value: {{ printf "s%s.%s" . $domain | quote }}
          {{- end }}
          {{- end }}
          - name: MYSQL_USERNAME
            value: {{ .Values.mysql.username | quote }}
          - name: MYSQL_PASSWORD
            value: {{ .Values.mysql.password | quote }}
          - name: HMAC_KEY
            value: {{ .Values.dbProxy.hmacKey | quote }}
          - name: MYSQL_DOMAIN
            value: {{ .Values.mysql.domain | quote }}
        resources:
{{ toYaml .Values.dbProxy.resources | indent 12 }}
        ports:
          - containerPort: 3306
            name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: db-proxy
{{ else }}
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: wikireplicas
spec:
  type: ExternalName
  externalName: {{ .Values.mysql.host | quote }}
{{ end }}
