mysql:
  domain: analytics.db.svc.eqiad.wmflabs
jupyterhub:
  hub:
    db:
      type: mysql
      upgrade: true
  ingress: 
    enabled: true
    hosts:
    - hub.paws.wmcloud.org
# So that we don't use the Bitnami charts in Cloud VPS deployment
mediawiki:
  enabled: false
