controller:
  name: controller
  image:
    repository: docker-registry.tools.wmflabs.org/nginx-ingress-controller
    tag: "v1.0.4"
    digest: sha256:a7fb797e0b1c919a49cf9b3f9bb90ebca39bc85d0edd11c9a5cf897da5eb5a3f
    pullPolicy: IfNotPresent
  config:
    # T241310: pass the incoming X-Forwarded-* headers to upstreams
    use-forwarded-headers: "true"
    # T243580: set default client_max_body_size to match dynamicproxy's setting
    proxy-body-size: 128M
    # T245426: set proxy_read_timeout to match dynamicproxy's setting
    proxy-read-timeout: "3600"
  resources:
    limits:
      cpu: 1
      memory: 2G
    requests:
      cpu: 0.5
      memory: 1G
  tolerations:
    - key: "ingressgen2"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                  - ingressgen2
  admissionWebhooks:
    enabled: false
  service:
    type: NodePort
    enableHttp: true
    enableHttps: false
    ports:
      http: 80
    nodePorts:
      http: 30002
      tcp:
        80: 30002
      udp: {}
  metrics:
    port: 10254
    enabled: true
  replicaCount: 2
  minAvailable: 1
  ingressClassResource:
    default: true
  # https://phabricator.wikimedia.org/T292771#7455219
  watchIngressWithoutClass: true
  # https://phabricator.wikimedia.org/T294330
  allowSnippetAnnotations: false
defaultBackend:
  enabled: false
podSecurityPolicy:
  enabled: true
