name: update container tags

on:
  pull_request:

jobs:
  update-container-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: git fetch
        run: |
          git fetch

      - name: update values.yaml
        run: |
          for i in renderer nbserve paws-hub jobber singleuser ; do
            if [[ $(git diff remotes/origin/master -- images/${i}/) ]]; then
            sed -i "s/tag: .* # ${i} tag managed by github actions$/tag: pr-${{ github.event.number }} # ${i} tag managed by github actions/" paws/values.yaml
            fi
          done

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'paws/values.yaml'
          author_name: Github Action
          author_email: auto@github.com
          branch: ${{ github.head_ref }}
          message: 'auto update of ${{ inputs.imagename }} tag'
          pull: --rebase --autostash
